### ISSUE TITLE
作者你好，在使用fsck.erofs分析华为emui9.1的system.img时总是提示

### ISSUE THREAD

**Issue by yuan22** [erofs/erofs-utils#9]
./fsck.erofs system1.img
<E> erofs: `.' or `..' dirent is missing @ nid 39
<E> erofs: `.' or `..' dirent is missing @ nid 0
<E> erofs: Found some filesystem corruption
请问下这个该怎么解决

**Comment by hsiangkao** [comment]
早期内部erofs商用定制版本，并没有在社区出现过，社区不会关注。

**Comment by hsiangkao** [comment]
建议您有需求联系华为官方，这里非问题关闭。
